package com.prismasolutions.DWbackend.enums;

public enum PeriodEnums {
    NONE,
    START_OF_ENTERING_TOPICS,
    END_OF_ENTERING_TOPICS,
    FIRST_TOPIC_ADVERTISMENT,
    FIRST_TOPIC_ADVERTISMENT_END,
    FIRST_ALOCATION,
    SECOND_TOPIC_ADVERTISMENT_END,
    SECOND_TOPIC_ADVERTIMENT_END,
    SECOND_ALLOCATION,
    IMPLEMENTATION_OF_TOPICS,
    DOCUMENTUM_UPLOADE,
    DIPLOMA_DEFEND;
}
